version: 2
jobs:
  build:
    docker:
      - image: node:11.10.1
    environment:
      CI: false

    steps:
      - checkout

      - run: yarn install
      - run: yarn start
      # run: yarn run test
      # run: yarn run build

workflows:
  version: 2
  build: 
    jobs:
      - build